spring:
  application:
    name: autodeal-backend
  profiles:
    active: dev # Define H2 como padr√£o inicial
  threads:
    virtual:
      enabled: true # Java 21+ aproveitando Virtual Threads

---
# Profile de Desenvolvimento (H2)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:autodealdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Ativa o ProblemDetail (RFC 7807) nativo do Spring 3
spring.mvc.problemdetails.enabled: true